name = "StructuredDistances"
uuid = "4b10685a-d40a-47ba-91ef-340327e5d163"
authors = ["George Bolt g.bolt@lancaster.ac.uk"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
